// https://wiki.rage.mp/index.php?title=HUD_Components
export enum HudComponent {
    Hud,
    HudWantedStars,
    HudWeaponIcon,
    HudCash,
    HudMpCash,
    HudMpMessage,
    HudVehicleName,
    HudAreaName,
    HudVehicleClass,
    HudStreetName,
    HudHelpText,
    HudFloatingHelpText1,
    HudFloatingHelpText2,
    HudCashChange,
    HudReticle,
    HudSubtitleText,
    HudRadioStations,
    HudSavingGame,
    HudGameStream,
    HudWeaponWheel,
    HudWeaponWheelStats,
    MaxHudComponents,
    MaxHudWeapons,
    MaxScriptedHudComponents = 141
}
