// https://wiki.rage.mp/index.php?title=Vehicle_Mods
enum VehicleMod {
    Spoiler,
    FrontBumpers,
    RearBumper,
    Skirts,
    Exhaust,
    Frame,
    Grille,
    Hood,
    Fenders,
    RearFenders,
    Roof,
    Engine,
    Brakes,
    Transmission,
    Horn,
    Suspension,
    Armor,
    FrontWheels = 23,
    BackWheels,
    Plate,
    Vanity,
    Trim,
    Ornaments,
    Dashboard,
    Dials,
    DoorSpeaker,
    Seats,
    SteeringWheel,
    ShiftLever,
    Plaques,
    Speakers,
    Trunk,
    Hydraulics,
    EngineBlock,
    AirFilter,
    Struts,
    ArchCover,
    Aerials,
    Visor,
    Tank,
    Details,
    Livery = 48
}

export default VehicleMod
